openapi: 3.0.3
info:
  title: API de pedidos
  description: API monitorar e coordenar pedidos
  version: 0.0.1
servers: 
-  url: https://mockapi.io
   description: api de teste 
paths:
  /api/pedidos:
    post:
      summary: cria um novo pedido
      requestBody:
        content:
          application/json:
           schema:
             type: object
             properties:
              idCliente:
                type: integer
              ruaParaEntrega:
                type: string
              numero:
                type: string
              complemento:
                type: string
              cep:
                type: number
              cidade:
                type: string
              uf:
                type: string
              itensDo:
                type: array
                items:
                   type: object
                   properties:
                    idProduto:
                      type: integer
                    estoque:
                      type: number
                    desconto:
                      type: number
                    precoSemDesconto:
                      type: number
      responses:
        201:
          description: pedido criado com sucesso
          content:
            application/json:
             schema:
               type: object
               properties:
                id:
                  type: integer
                idCliente:
                  type: integer
                ruaParaEntrega:
                  type: string
                numero:
                  type: string
                complemento:
                  type: string
                cep:
                  type: number
                cidade:
                  type: string
                uf:
                  type: string
                itensDo:
                  type: array
                  items:
                     type: object
                     properties:
                      idProduto:
                        type: integer
                      estoque:
                        type: number
                      desconto:
                        type: number
                      precoSemDesconto:
                        type: number
  /api/pedido/{id}:
    get:
      summary: Detalhando pedido pelo id
      parameters: 
      - name: id
        in: path
        schema:
          type: integer
        required: true
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  idCliente:
                    type: integer
                  ruaParaEntrega:
                    type: string
                  numero:
                    type: string
                  complemento:
                    type: string
                  cep:
                    type: number
                  cidade:
                    type: string
                  uf:
                    type: string
                  itensDo:
                    type: array
                    items:
                      type: object
                      properties:
                        idProduto:
                          type: integer
                        estoque:
                          type: number
                        desconto:
                          type: number
                        precoSemDesconto:
                          type: number