version: "3.9"
services:
    product:
        build: ./product
        container_name: product
        ports:
        - "3001:3001"
    account:
        build: ./account
        container_name: account
    mongodb:
        container_name: mongo-ecomm
        image: mongo
        environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=secret
        - MONGO_INITDB_DATABASE=ecomm-product
        ports:
        - "27017:27017"
        command: mongod --bind_ip=0.0.0.0