version: "3.9"
services:
    product:
        build: ./product
        container_name: product
        ports:
        - "3001:3001"
    account:
        build: ./account
        container_name: account
        ports:
        - "3002:3002"
    finance:
        build: ./finance
        container_name: finance
        ports:
        - "3003:3003"
    mongodb:
        container_name: mongo-ecomm
        image: mongo:5.0
        environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=secret
        - MONGO_INITDB_DATABASE=ecomm
        ports:
        - "27017:27017"
        command: mongod --bind_ip=0.0.0.0
    mysql:
        container_name: mysql-ecomm
        image: mysql
        restart: always
        environment:
        - MYSQL_ROOT_PASSWORD=secret
        ports:
        - "3306:3306"
        volumes:
        - todo-mysql-data:/var/lib/mysql

volumes:
  todo-mysql-data: