openapi: 3.0.3
info:
  title: API de usuarios
  description: API monitorar e coordenar contas de usuarios
  version: 0.0.1
servers: 
-  url: https://mockapi.io
   description: api de teste 
paths:
  /api/user:
    get:
      summary: Listando usuarios
      responses:
        200:
          description: Sucesso
          content:
            application/json:
             schema:
               type: array
               items:
                 type: object
                 properties:
                  nome:
                    type: string
                  email:
                    type: string
                  senha:
                    type: string
                  cpf:
                    type: string
                  telefone:
                    type: number
                  endereco:
                    type: array
                    items:
                       type: object
                       properties:
                        rua:
                          type: string
                        numero:
                          type: number
                        complemento:
                          type: string
                        cep:
                          type: number
                        cidade:
                          type: string
                        uf:
                          type: string
  /api/admin/user:
    post:
      summary: Inserindo novo usuario
      requestBody:
        content:
          application/json:
           schema:
             type: object
             properties:
              nome:
                type: string
              email:
                type: string
              senha:
                type: string
              cpf:
                type: string
              telefone:
                type: number
              endereco:
                type: array
                items:
                   type: object
                   properties:
                    rua:
                      type: string
                    numero:
                      type: number
                    complemento:
                      type: string
                    cep:
                      type: number
                    cidade:
                      type: string
                    uf:
                      type: string
      responses:
        201:
          description: categoria criada com sucesso
          content:
            application/json:
             schema:
               type: object
               properties:
                id:
                  type: integer
                nome:
                  type: string
                email:
                  type: string
                senha:
                  type: string
                cpf:
                  type: string
                telefone:
                  type: number
                endereco:
                  type: array
                  items:
                     type: object
                     properties:
                      rua:
                        type: string
                      numero:
                        type: number
                      complemento:
                        type: string
                      cep:
                        type: number
                      cidade:
                        type: string
                      uf:
                        type: string
  /api/user/{id}:
    get:
      summary: Detalhando usuario pelo id
      parameters: 
      - name: id
        in: path
        schema:
          type: integer
        required: true
      responses:
        200:
          description: Sucesso
          content:
            application/json:
             schema:
                 type: object
                 properties:
                  id:
                    type: integer
                  nome:
                    type: string
                  email:
                    type: string
                  senha:
                    type: string
                  cpf:
                    type: string
                  telefone:
                    type: number
                  endereco:
                    type: array
                    items:
                       type: object
                       properties:
                        rua:
                          type: string
                        numero:
                          type: number
                        complemento:
                          type: string
                        cep:
                          type: number
                        cidade:
                          type: string
                        uf:
                          type: string
  /api/admin/user/{id}:
    put:
      summary: Atualizando usuario
      parameters: 
      -   name: id
          in: path
          schema:
            type: integer
          required: true
      requestBody:
        content:
          application/json:
           schema:
             type: object
             properties:
              id:
                type: integer
              nome:
                type: string
              email:
                type: string
              senha:
                type: string
              cpf:
                type: string
              telefone:
                type: number
              endereco:
                type: array
                items:
                   type: object
                   properties:
                    rua:
                      type: string
                    numero:
                      type: number
                    complemento:
                      type: string
                    cep:
                      type: number
                    cidade:
                      type: string
                    uf:
                      type: string
      responses:
        200:
          description: Sucesso
          content:
            application/json:
             schema:
                 type: object
                 properties:
                  id:
                    type: integer
                  nome:
                    type: string
                  email:
                    type: string
                  senha:
                    type: string
                  cpf:
                    type: string
                  telefone:
                    type: number
                  endereco:
                    type: array
                    items:
                       type: object
                       properties:
                        rua:
                          type: string
                        numero:
                          type: number
                        complemento:
                          type: string
                        cep:
                          type: number
                        cidade:
                          type: string
                        uf:
                          type: string
    delete:
      summary: Deleta um user
      parameters: 
      -   name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        204:
          description: deletado com sucesso