openapi: 3.0.3
info:
  title: API de produtos
  description: API monitorar e coordenar loja ecomm.
  version: 0.0.1
paths:
  /api/categories:
    get:
      summary: Recupera as categorias
      responses:
        200:
          description: Sucesso
          content:
            application/json:
             schema:
               type: array
               items:
                 type: object
                 properties:
                   id:
                    type: string
                   nome:
                    type: string
                   status:
                    type: string
                    enum: [ATIVA, INATIVA]
        404:
          description: a categoria não foi encontrada ou não existe
          content:
            application/json:
              example: "A categoria não existe"
        500:
          description: problema de servidor
          content:
            application/json:
              example: "erro no servidor"