openapi: 3.0.3
info:
  title: API de produtos
  description: API monitorar e coordenar loja ecomm.
  version: 0.0.1
servers: 
-  url: https://mockapi.io
   description: api de teste 
paths:
  /api/categories:
    get:
      summary: Recupera as categorias
      responses:
        200:
          description: Sucesso
          content:
            application/json:
             schema:
               type: array
               items:
                 type: object
                 properties:
                   id:
                    type: string
                   nome:
                    type: string
                   status:
                    type: string
                    enum: [ATIVA, INATIVA]
        404:
          description: a categoria não foi encontrada ou não existe
          content:
            application/json:
              example: "A categoria não existe"
  /api/admin/categories:
    post:
      summary: Criando uma categoria 
      requestBody:
        content:
          application/json:
           schema:
             type: object
             properties:
               nome:
                type: string
      responses:
        201:
          description: categoria criada com sucesso
          content:
            application/json:
             schema:
               type: object
               properties:
                 id:
                  type: string
                 nome:
                  type: string
                 status:
                  type: string
