openapi: 3.0.3
info:
  title: API de produtos
  description: API monitorar e coordenar loja ecomm.
  version: 0.0.1
servers: 
-  url: https://mockapi.io
   description: api de teste 
paths:
  /api/categories:
    get:
      summary: Recupera as categorias
      responses:
        200:
          description: Sucesso
          content:
            application/json:
             schema:
               type: array
               items:
                 type: object
                 properties:
                   id:
                    type: string
                   nome:
                    type: string
                   status:
                    type: string
                    enum: [ATIVA, INATIVA]
        404:
          description: a categoria não foi encontrada ou não existe
          content:
            application/json:
              example: "A categoria não existe"
  /api/categories/{id}:
    get:
      summary: Recupera as categorias
      parameters: 
      - name: id
        in: path
        schema:
          type: integer
        required: true
      responses:
        200:
          description: Sucesso
          content:
            application/json:
             schema:
                 type: object
                 properties:
                   id:
                    type: string
                   nome:
                    type: string
                   status:
                    type: string
                    enum: [ATIVA, INATIVA]
        404:
          description: a categoria não foi encontrada ou não existe
          content:
            application/json:
              example: "A categoria não existe"
 
    post:
      summary: Criando uma categoria 
      requestBody:
        content:
          application/json:
           schema:
             type: object
             properties:
               nome:
                type: string
      responses:
        201:
          description: categoria criada com sucesso
          content:
            application/json:
             schema:
               type: object
               properties:
                 id:
                  type: string
                 nome:
                  type: string
                 status:
                  type: string
  /api/admin/categories/{id}:
    put:
      summary: Atualizando categorias
      parameters: 
      -   name: id
          in: path
          schema:
            type: integer
          required: true
      requestBody:
        content:
          application/json:
           schema:
             type: object
             properties:
                   id:
                    type: string
                   nome:
                    type: string
                   status:
                    type: string
                    enum: [ATIVA, INATIVA]
      responses:
        200:
          description: Sucesso
          content:
            application/json:
             schema:
                 type: object
                 properties:
                   id:
                    type: string
                   nome:
                    type: string
                   status:
                    type: string
                    enum: [ATIVA, INATIVA]
    delete:
      summary: Deleta uma categoria
      parameters: 
      -   name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        204:
          description: deletado com sucesso
    patch:
      summary: Ativa uma categoria
      parameters: 
      -   name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        200:
          description: ativação feita com sucesso
          content:
            application/json:
             schema:
                 type: object
                 properties:
                   id:
                    type: string
                   nome:
                    type: string
                   status:
                    type: string
                    enum: [ATIVA, INATIVA]